name: Release Windows

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  windows-release:
    uses: ./.github/workflows/fix-nsis.yml
    with:
      release_tag: ${{ github.ref_name }}
